name : test react app 

on : 
    push:
      branches:
        -main


jobs:
    get_environment_name_from_git_ref:
        name: get_environment_value
        runs-on : ubuntu-latest
        steps:
            -name : checkout
             uses : action/checkout@v3

            -name: Set environment name dynamically
            id: setenv
            run:  echo "env" >> $GITHUB_OUTPUT

        outputs:
          env: ${{ steps.setenv.outputs.env }}
      
    test_react_app:
        name: test react app
        runs-on: ubuntu-latest
        needs: [get_environment_name_from_git_ref]
        environment : ${{needs.get_environment_name_from_git_ref.outputs.env}}
        steps:
            -name: checlout
            uses : action/checkout@v3

            -name : install npm
            uses: actions/setup-node@v3
            with:
              node-version: 16.X

            -name: install npm packages
            run : npm install

            -name : test case
            run : npm test

    Build_app :
        name: Build app
        runs-on: ubuntu-latest
        needs: [get_environment_name_from_git_ref]
        environment : ${{needs.get_environment_name_from_git_ref.outputs.env}}
        steps:
            -name : checkout
            uses: action/checkout@v3

            -name : install npm 
            uses : action/setup-node@v3
            with:
                node-version: 16.X
            
            -name : install node packages
            run : npm install

            -name : build app
            run : npm run build





